"""Icon constants for Telegram notifications."""

SUCCESS_ICON = "✅"
WARNING_ICON = "⚠️"
DANGER_ICON = "🚨"
AI_ICON = "🧠"
RISK_ICON = "📌"
TREND_ICON = "📈"
TIME_ICON = "🕒"
FIRE_ICON = "🔥"
MONEY_ICON = "💰"
CHECK_ICON = "📊"
BRAIN_ICON = "🤖"
SHIELD_ICON = "🛡️"
